<?php
namespace app\admin\controller;


use app\admin\model\UserModel;
use think\Controller;
use think\Db;
use think\Model;
use think\Request;
use app\admin\model\MenuModel;
use think\Session;

class CommonController extends Controller{

    public function _initialize()
    {
        Session::init();
        parent::_initialize(); // TODO: Change the autogenerated stub
        if (!defined('MODULE_NAME')){define('MODULE_NAME', $this->request->module());}
        if (!defined('CONTROLLER_NAME')){define('CONTROLLER_NAME', $this->request->controller());}
        if (!defined('ACTION_NAME')){define('ACTION_NAME', $this->request->action());}
    }

    public function __construct(Request $request)
    {
        parent::__construct($request);
        $this->check_login();
    }

    public function initMenu(){
        $menu = cache('Menu');
        if(!$menu){
            $menuModel = new MenuModel();
            $menu = $menuModel->menu_cache();
        }
        return $menu;
    }

    private function load_app_admin_menu_lang(){
        if (config('LANG_SWITCH_ON',null,false)){
            $admin_menu_lang_file=APP_PATH."/Common/Lang/".LANG_SET."/admin_menu.php";
            if(is_file($admin_menu_lang_file)){
                $lang = include $admin_menu_lang_file;
                lang($lang);
            }
        }
    }
    private function check_login(){

        if(session('ADMIN_ID')){
            $users_obj = new UserModel();
            $id = session('ADMIN_ID');
            $user=$users_obj->where("id = $id")->find();
            if(!$this->check_access($id)){
                $this->error("您没有访问权限！");
                exit();
            }
            $this->assign("admin",$user);
        }else{
            if(input()->isAjax){
                $this->error("您还没有登录！",url("admin/public/login"));
            }else{
                header("Location:".url("admin/public/login"));
                exit();
            }

        }
    }

    private function check_access($uid){
        //如果用户角色是1，则无需判断
        if($uid == 1){
            return true;
        }
        $rule = MODULE_NAME.CONTROLLER_NAME.ACTION_NAME;
        $no_need_check_rules=array("HomeIndexindex","HomeMainindex");

        if( !in_array($rule,$no_need_check_rules) ){
            return auth_check($uid);
        }else{
            return true;
        }
    }

    /**
     *  排序 排序字段为listorders数组 POST 排序字段为：listorder
     * @param $model Model
     * @return bool
     */
    protected function _listorders(Model $model) {
        if (!is_object($model)) {
            return false;
        }
        $pk = $model->getPk(); //获取主键名称

        $ids = $_POST['listorders'];

        foreach ($ids as $key => $r) {
            $data['listorder'] = $r;
            $model->where(array($pk => $key))->update($data);
        }
        return true;
    }
}